skinparam monochrome true
skinparam ranksep 20
skinparam dpi 150
skinparam packageTitleAlignment left
skinparam usecaseBorderThickness 0.4
skinparam defaultFontSize 12
skinparam rectangleBorderThickness 1
hide methods

class Category {
  name: string
  icon: string
}

class Action {
  createdAt: Date
}

class Change {
  type: ChangeType
  rowId: int
  orderIndex: int
}

enum ChangeType {
  Insert
  Update
  Delete
}

class Table {
  name: string
}

class Column {
  name: string
  type: string
}

class Value {
  oldValue: string
  newValue: string
}

class Channel {
  id: int
}

Channel o-- Action
Action o-- Category
Action o-- Change
Change o-- Table
Change o-- ChangeType
Table o-- Channel
Column o-down- Table 
Value o-- Column
Value o-- Change